### ISSUE TITLE
Is this bundle still maintained?

### ISSUE THREAD

**Issue by jfenal** [ansible-provisioning/ansible-provisioning#31]
The question is in the subject.

**Comment by simonmcc** [comment]
well, it still works with the hardware we're using - is supporting for something you have missing?

**Comment by dagwieers** [comment]
We are going to move some of this stuff back into Ansible.
We created this repository when these modules were removed from Ansible after being first accepted. 
The reason for removing them was that the author couldn't test them (lacking the hardware) so couldn't vouch for them. I think we have moved on since then ;-)

**Comment by dagwieers** [comment]
So yes !
